---
- name: create runtime-data directory
  file:
      path: '{{ syslog_ng_config_dest }}/runtime-data'
      state: directory

- name: copy certificate files
  copy:
    content: "{{ syslog_ng_key | b64decode }}"
    dest: "{{ syslog_ng_config_dest }}/runtime-data/{{ syslog_ng_key_name }}"
    mode: 0600

- name: copy certificate files
  copy:
    content: "{{ syslog_ng_cert | b64decode }}"
    dest: "{{ syslog_ng_config_dest }}/runtime-data/{{ syslog_ng_cert_name }}"

- name: copy trusted CA certificates to /etc/ssl/certs
  copy:
    content: "{{ syslog_ng_ca_cert | b64decode }}"
    dest: "/etc/ssl/certs/{{ syslog_ng_ca_cert_name }}"
  when: syslog_ng_ca_cert
  notify:
    - syslog_ng_certificate_rehash