---
- name: Import syslog tls secret
  become: no
  command: "sudo kubectl create secret generic syslog-tls-secret --from-file=syslog-cert.pem={{ syslog_ng_config_dest }}/runtime-data/{{ syslog_ng_cert_name }} --from-file=syslog-key.pem={{ syslog_ng_config_dest }}/runtime-data/{{ syslog_ng_key_name }} --namespace={{ helm_namespace }}"
  when: syslog_ng_source_sandbox_protocol == "tls"
  register: result
  failed_when:
    - "'FAILED' in result.stderr"
    - '"already exist" not in result.stdout'
    
- name: Install Syslog-ng Helm chart
  community.kubernetes.helm:
    name: "kypo-crp-syslog"
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ helm_namespace }}"
    chart_ref: "{{ role_path }}/../../helm/kypo-crp-syslog"
    chart_version: "{{ syslog_chart_version }}"
    values: "{{ lookup('template', 'templates/helm_values.yaml.j2') | from_yaml  }}"
