---
- name: Ensure k8s namespace is created
  become: no
  kubernetes.core.k8s:
    name: "{{ helm_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  
- name: Install Elk chart
  community.kubernetes.helm:
    name: "kypo-crp-elk"
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ helm_namespace }}"
    chart_ref: "{{ role_path }}/../../helm/kypo-crp-elk"
    chart_version: "{{ elk_chart_version }}"
