---
- name: get oidc providers configurations
  uri:
      url: '{{ item.url | regex_replace("/$", "") }}/.well-known/openid-configuration'
      validate_certs: no
  loop: '{{ kypo_crp_oidc_providers }}'
  register: kypo_crp_oidc_configurations_output

- name: set kypo_crp_oidc_configurations list variable
  set_fact:
      kypo_crp_oidc_configurations: '{{ kypo_crp_oidc_configurations_output.results | map(attribute="json") | list }}'

- name: get certificate subject hash
  command: openssl x509 -noout -hash -in {{ kypo_crp_runtime_dest }}/{{ kypo_crp_cert_name }}
  changed_when: False
  register: kypo_crp_cert_hash

- name: set certificate subject hash variable
  set_fact:
      kypo_crp_cert_hash: '{{ kypo_crp_cert_hash.stdout }}'
