apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
