- name: Ensure k8s namespace is created
  become: no
  kubernetes.core.k8s:
    name: "{{ helm_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  
- name: Import git keys secrets
  become: no
  command: "sudo kubectl create secret generic internal-git-ssh-keys --from-file=git-ssh-key={{ kypo_crp_runtime_dest }}/{{ kypo_crp_git_internal_ssh_key_filename }} --from-file=git-ssh-key.pub={{ kypo_crp_runtime_dest }}/{{ kypo_crp_git_internal_ssh_key_filename }}.pub --namespace={{ helm_namespace }}"
  register: result
  failed_when:
    - "'FAILED' in result.stderr"
    - '"already exist" not in result.stdout'
    
- name: Install Kypo head Helm chart
  community.kubernetes.helm:
    name: "kypo-crp-git-internal"
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ helm_namespace }}"
    chart_ref: "{{ role_path }}/../../helm/kypo-crp-git-internal"
    chart_version: "{{ git_chart_version }}"