
- name: ensure the existence of runtime directory
  file:
    path: '{{ kypo_crp_runtime_dest }}'
    state: directory
    recurse: yes

- name: generate ssh key
  openssh_keypair:
    path: '{{ kypo_crp_runtime_dest }}/{{ kypo_crp_git_internal_ssh_key_filename }}'
  register: kypo_crp_git_internal_keypair_output

- name: slurp key
  slurp:
    path: '{{ kypo_crp_runtime_dest }}/{{ kypo_crp_git_internal_ssh_key_filename }}'
  register: kypo_crp_git_internal_slurp_private

- name: save private and public keys
  set_fact:
    kypo_crp_git_internal_private_key: '{{ kypo_crp_git_internal_slurp_private.content }}'
    kypo_crp_git_internal_public_key: '{{ kypo_crp_git_internal_keypair_output.public_key | b64encode }}'
