{{- with .Values.answersStorage }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
data:
  kypo-answers-storage.properties: |
    ## server port for a given service, e.g., 8086
    server.port=8087
    ## server context path (the base url for the service), e.g., /kypo-answer-storage/api/v1
    server.servlet.context-path={{ $.Values.answersStorage.contextPath }}
    ## microservice name which is used in user management service for identification of this service, e.g. kypo-smart-assistant
    microservice.name=kypo-answers-storage

    ## Allows you to specify allowed origins for CORS mapping. You could set it as, e.g., http://domain1.com, http://domain2.com, etc. The default value is: *
    cors.allowed.origins={{ $.Values.kypoCrpUrl }}

    # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
    spring.datasource.url=jdbc:postgresql://{{ $.Values.databaseHost }}:5432/kypo-answers-storage
    spring.datasource.username=postgres
    spring.datasource.password=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto= 
    spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

    ## Configuring Jackson serializer for converting Java 8 dates to ISO format
    spring.jackson.serialization.write_dates_as_timestamps=false 
    ## all atributes in JSON are in SNAKE_CASE
    spring.jackson.property-naming-strategy=SNAKE_CASE
    spring.flyway.enabled=true
{{- end -}}
