{{- with .Values.angularFrontend }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
data:
  kypo-config.json: |
    { 
      "roleMapping": {
        "uagAdmin": "ROLE_USER_AND_GROUP_ADMINISTRATOR",
        "trainingDesigner": "ROLE_TRAINING_DESIGNER",
        "trainingOrganizer": "ROLE_TRAINING_ORGANIZER",
        "trainingTrainee": "ROLE_TRAINING_TRAINEE",
        "sandboxDesigner": "ROLE_KYPO-SANDBOX-SERVICE_DESIGNER",
        "sandboxOrganizer": "ROLE_KYPO-SANDBOX-SERVICE_ORGANIZER"
      },
      "trainingAgendaConfig": {
        "pollingPeriod": 5000,
        "defaultPaginationSize": 10,
        "visualizationConfig": {
          "trainingBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.training.contextPath }}",
          "adaptiveBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.adaptiveTraining.contextPath }}",
          "elasticSearchBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.elasticsearch.contextPath }}"
        },
        "kypo2TopologyConfig": {
          "topologyRestUrl": "{{ $.Values.kypoCrpUrl }}{{ $.Values.sandbox.contextPath }}",
          "decoratorsRestUrl": "",
          "defaultDecoratorRefreshPeriodInSeconds": 3,
          "useRealTime": false,
          "useDecorators": false,
          "guacamoleConfig": {
            "url": "test",
            "username": "test",
            "password": "test"
          }
        }
      },
      "trainingApiConfig": {
        "trainingBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.training.contextPath }}",
        "adaptiveBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.adaptiveTraining.contextPath }}"
      },
      "sandboxAgendaConfig": {
        "pollingPeriod": 5000,
        "defaultPaginationSize": 10,
        "kypo2TopologyConfig": {
          "topologyRestUrl": "{{ $.Values.kypoCrpUrl }}{{ $.Values.sandbox.contextPath }}",
          "decoratorsRestUrl": "",
          "defaultDecoratorRefreshPeriodInSeconds": 3,
          "useRealTime": false,
          "useDecorators": false,
          "guacamoleConfig": {
            "url": "test",
            "username": "test",
            "password": "test"
          }
        }
      },
      "sandboxApiConfig": {
        "sandboxRestBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.sandbox.contextPath }}"
      },
      "userAndGroupAgendaConfig": {
        "defaultPaginationSize": 10
      },
      "userAndGroupApiConfig": {
        "userAndGroupRestBasePath": "{{ $.Values.kypoCrpUrl }}{{ $.Values.userAndGroup.contextPath }}"
      },
      "authConfig": {
        "guardMainPageRedirect": "home",
        "guardLoginPageRedirect": "login",
        "interceptorAllowedUrls": [
          "{{ $.Values.kypoCrpUrl }}"
        ],
        "authorizationStrategyConfig": {
          "authorizationUrl": "{{ $.Values.kypoCrpUrl }}{{ $.Values.userAndGroup.contextPath }}users/info"
        },
        "providers": [
{{- range $index, $element := $.Values.kypoCrpOidcs }}
          {
            "label": "{{ $element.label }}",
            "textColor": "white",
            "backgroundColor": "#002776",
            "oidcConfig": {
              "requireHttps": true,
              "issuer": "{{ $element.url }}",
              "clientId": "{{ $element.clientId }}",
              "redirectUri": "{{ $.Values.kypoCrpUrl }}",
              "scope": "openid email profile",
              "logoutUrl": "{{ $element.logoutUrl }}",
              "postLogoutRedirectUri": "{{ $.Values.kypoCrpUrl }}/logout-confirmed",
              "silentRefreshRedirectUri": "{{ $.Values.kypoCrpUrl }}/silent-refresh.html",
              "clearHashAfterLogin": true,
              "strictDiscoveryDocumentValidation": false,
              "skipIssuerCheck": true,
              "oidc": true
            }
          }{{if $index}},{{end}}
{{- end }}
        ]
      },
      "version": "v21.06"
    }
{{- end -}}
