{{- with .Values.smartAssistant }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
data:
  kypo-adaptive-smart-assistant.properties: |
    ## server port for a given service, e.g., 8086
    server.port=8086
    ## server context path (the base url for the service), e.g., /kypo-adaptive-training/api/v1
    server.servlet.context-path={{ $.Values.smartAssistant.contextPath }}
    ## microservice name which is used in user management service for identification of this service, e.g. kypo-smart-assistant
    microservice.name=kypo-adaptive-smart-assistant

    ## Allows you to specify allowed origins for CORS mapping. You could set it as, e.g., http://domain1.com, http://domain2.com, etc. The default value is: *
    cors.allowed.origins={{ $.Values.kypoCrpUrl }}

    # calling user-and-group project, e.g., https://localhost:8084/kypo-rest-user-and-group/api/v1
    user-and-group-server.uri=http://{{ $.Values.userAndGroup.name }}:{{ $.Values.userAndGroup.port }}{{ $.Values.userAndGroup.contextPath }}
    # calling kypo-openstack, e.g., http://localhost:8080/kypo-openstack/api/v1
    openstack-server.uri=http://{{ $.Values.sandbox.name }}:{{ $.Values.sandbox.port }}{{ $.Values.sandbox.contextPath }}
    # calling kypo-elasticsearch-service, e.g., http://elastic-service:8085/kypo-elastic/api/v1
    elasticsearch-service.uri=http://{{ $.Values.elasticsearch.name }}:{{ $.Values.elasticsearch.port }}{{ $.Values.elasticsearch.contextPath }}

    # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
    spring.datasource.url=jdbc:postgresql://{{ $.Values.databaseHost }}:5432/kypo-adaptive-smart-assistant
    spring.datasource.username=postgres
    spring.datasource.password=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
    spring.data.jpa.repositories.enabled=true
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=
    spring.jpa.show-sql=true 
    spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

    # spring-cloud
    spring.cloud.refresh.enabled = false
    ## disables the settings in application.properties in resource folder
    spring.jmx.enabled=false
    ## Configuring Jackson serializer for converting Java 8 dates to ISO format
    spring.jackson.serialization.write_dates_as_timestamps=false 
    ## all atributes in JSON are in SNAKE_CASE
    spring.jackson.property-naming-strategy=SNAKE_CASE

    ## the requirement for ssl, e.g., false
    security.require-ssl=false
    management.health.refresh.enabled=false

{{- end -}}
